export const ADMIN_ROUTE = '/Admin'
export const ABOUT_ROUTE = '/AboutPage'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const GROUP_ROUTE = '/group'
export const CHILD_ROUTE = '/children'
